
export const LOADING = "LOADING"
export const SUCCESS = "SUCCESS"
export const ERROR = "ERROR"
export const NODATA = "NODATA"
export const RESET = "RESET"

export const BOOKMARKLOADING = "BOOKKMARKLOADING"
export const BOOKMARKSUCCESS = "BOOKMARKSUCCESS"
export const BOOKMARKERROR = "BOOKMARKERROR"
export const BOOKMARKNODATA = "BOOKMARKNODATA"

export const REGISTER = "REGISTER"

export const LOGIN = "LOGIN"


// CATEGORIES:=====
export const ALL_CATEGORIES_LOADING = "ALL_CATEGORIES_LOADING"
export const ALL_CATEGORIES = "ALL_CATEGORIES";
export const FEATURED_CATEGORIES_LOADING = "FEATURED_CATEGORIES_LOADING"
export const FEATURED_CATEGORIES = "FEATURED_CATEGORIES";
export const GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING"
export const GET_CATEGORY = "GET_CATEGORY";


//CITIES:=========
export const ALL_CITIES_LOADING = "ALL_CITIES_LOADING"
export const ALL_CITIES = "ALL_CITIES";
export const GET_CITY_LOADING = "GET_CITY_LOADING"
export const GET_CITY = "GET_CITY";
export const GET_CITY_BY_COUNTRY_LOADING = "GET_CITY_BY_COUNTRY_LOADING"
export const GET_CITIES_BY_COUNTRY = "GET_CITIES_BY_COUNTRY"


//COMPANIES:======
export const ALL_COMPANIES_LOADING = "ALL_COMPANIES_LOADING"
export const ALL_COMPANIES = "ALL_COMPANIES";
export const GET_COMPANIES_LOADING = "GET_COMPANIES_LOADING"
export const GET_COMPANY = "GET_COMPANY";
export const NO_COMPANIES_LOADING = "NO_COMPANIES_LOADING"
export const NO_COMPANY = "NO_COMPANY";
export const CREATE_COMPANIES_LOADING = "CREATE_COMPANIES_LOADING"
export const CREATE_COMPANY = "CREATE_COMPANY";


//COUNTRIES:=====
export const ALL_COUNTRIES_LOADING = "ALL_COUNTRIES_LOADING"
export const ALL_COUNTRIES = "ALL_COUNTRIES";
export const GET_COUNTRY_LOADING = "GET_COUNTRY_LOADING"
export const GET_COUNTRY = "GET_COUNTRY";


//JOBS:========
export const ALL_JOBS_LOADING = "ALL_JOBS_LOADING"
export const ALL_JOBS = "ALL_JOBS";
export const RECENT_JOBS_LOADING = "RECENT_JOBS_LOADING"
export const RECENT_JOBS = "RECENT_JOBS";
export const GET_JOBS_LOADING = "GET_JOBS_LOADING"
export const GET_JOB = "GET_JOB";
export const GET_JOBS_BY_CATEGORY_LOADING = "GET_JOBS_BY_CATEGORY_LOADING"
export const GET_JOBS_BY_CATEGORY = "GET_JOBS_BY_CATEGORY";
export const GET_JOBS_BY_COUNTRY_LOADING = "GET_JOBS_BY_COUNTRY_LOADING"
export const GET_JOBS_BY_COUNTRY = "GET_JOBS_BY_COUNTRY";
export const GET_JOBS_BY_CITY_LOADING = "GET_JOBS_BY_CITY_LOADING"
export const GET_JOBS_BY_CITY = "GET_JOBS_BY_CITY";
export const GET_JOBS_BY_COMPANY_LOADING = "GET_JOBS_BY_COMPANY_LOADING"
export const GET_JOBS_BY_COMPANY = "GET_JOBS_BY_COMPANY";
export const GET_JOBS_BY_PROVIDER_LOADING = "GET_JOBS_BY_PROVIDER_LOADING"
export const GET_JOBS_BY_PROVIDER = "GET_JOBS_BY_PROVIDER"
export const GET_JOBS_BY_PROVIDER_FEATURED_LOADING = "GET_JOBS_BY_PROVIDER_FEATURED_LOADING"
export const GET_JOBS_BY_PROVIDER_FEATURED = "GET_JOBS_BY_PROVIDER_FEATURED"
export const GET_RECOMMENDED_JOBS_LOADING = "GET_RECOMMENDED_JOBS_LOADING"
export const GET_RECOMMENDED_JOBS = "GET_RECOMMENDED_JOBS"
export const JOB_SEARCH_LOADING = "JOB_SEARCH_LOADING"
export const JOB_SEARCH = "JOB_SEARCH";

//INTERACTIONS:=====
export const ALL_INTERACTIONS_LOADING = "ALL_INTERACTIONS_LOADING"
export const ALL_INTERACTIONS = "ALL_INTERACTIONS";
export const GET_INTERACTION_LOADING = "GET_INTERACTION_LOADING"
export const GET_INTERACTIONS = "GET_INTERACTION";
export const GET_INTERACTIONS_BY_USER_LOADING = "GET_INTERACTIONS_BY_USER_LOADING"
export const GET_INTERACTIONS_BY_USER = "GET_INTERACTIONS_BY_USER";
export const GET_INTERACTIONS_BY_TYPE_LOADING = "GET_INTERACTIONS_BY_TYPE_LOADING"
export const GET_INTERACTIONS_BY_TYPE = "GET_INTERACTIONS_BY_TYPE";


//PLANS:========
export const ALL_PLANS_LOADING = "ALL_PLANS_LOADING"
export const ALL_PLANS = "ALL_PLANS";
export const GET_PLAN_BY_ID_LOADING = "GET_PLAN_BY_ID_LOADING"
export const GET_PLAN_BY_ID = "GET_PLAN_BY_ID";
export const GET_PLAN_BY_TYPE_LOADING = "GET_PLAN_BY_TYPE_LOADING"
export const GET_PLAN_BY_TYPE = "GET_PLAN_BY_TYPE";


//REPORTS:=======
export const ALL_REPORTS_LOADING = "ALL_REPORTS_LOADING"
export const ALL_REPORTS = "ALL_REPORTS";
export const GET_REPORT_BY_ID_LOADING = "GET_REPORT_BY_ID_LOADING"
export const GET_REPORT_BY_ID = "GET_REPORT_BY_ID";


//SEEKERS:======
export const ALL_SEEKERS_LOADING = "ALL_SEEKERS_LOADING"
export const ALL_SEEKERS = "ALL_SEEKERS";
export const GET_SEEKER_LOADING = "GET_SEEKER_LOADING"
export const GET_SEEKER = "GET_SEEKER";
export const CHECK_SEEKER_LOADING = "CHECK_SEEKER_LOADING"
export const CHECK_SEEKER = "CHECK_SEEKER";
export const UPDATE_SEEKER_LOADING = "UPDATE_SEEKER_LOADING"
export const UPDATE_SEEKER = "UPDATE_SEEKER";
export const RESET_SEEKER_LOADING = "RESET_SEEKER_LOADING"
export const RESET_SEEKER = "RESET_SEEKER";
export const RECOMMENDED_SEEKER_LOADING = "RECOMMENDED_SEEKER_LOADING"
export const RECOMMENDED_SEEKER = "RECOMMENDED_SEEKER";


//Tags:=========
export const GET_ALL_TAGS_LOADING = "GET_ALL_TAGS_LOADING"
export const GET_ALL_TAGS = "GET_ALL_TAGS";
export const GET_TOP_TAGS_LOADING = "GET_TOP_TAGS_LOADING"
export const GET_TOP_TAGS = "GET_TOP_TAGS";


//APPLIED:=====
export const ALL_APPLIED_LOADING = "ALL_APPLIED_LOADING"
export const ALL_APPLIED = "ALL_APPLIED";
export const GET_APPLIED_BY_ID_LOADING = "GET_APPLIED_BY_ID_LOADING"
export const GET_APPLIED_BY_ID = "GET_APPLIED_BY_ID";
export const GET_APPLIED_BY_JOB_LOADING = "GET_APPLIED_BY_JOB_LOADING"
export const GET_APPLIED_BY_JOB = "GET_APPLIED_BY_JOB";
export const GET_APPLIED_BY_COMPANY_LOADING = "GET_APPLIED_BY_COMPANY_LOADING"
export const GET_APPLIED_BY_COMPANY = "GET_APPLIED_BY_COMPANY";


//CV:=======
export const ALL_CV_LOADING = "ALL_CV_LOADING"
export const ALL_CV = "ALL_CV";
export const GET_CV_BY_ID_LOADING = "GET_CV_BY_ID_LOADING"
export const GET_CV_BY_ID = "GET_CV_BY_ID";
export const GET_COVER_BY_USER_LOADING = "GET_COVER_BY_USER_LOADING"
export const GET_COVER_BY_USER = "GET_COVER_BY_USER";
export const GET_CV_BY_USER_LOADING = "GET_CV_BY_USER_LOADING"
export const GET_CV_BY_USER = "GET_CV_BY_USER";
export const CREATE_CV_EDUCATION_LOADING = "CREATE_CV_EDUCATION_LOADING"
export const CREATE_CV_EDUCATION = "CREATE_CV_EDUCATION"
export const CREATE_CV_INTEREST_LOADING = "CREATE_CV_INTEREST_LOADING"
export const CREATE_CV_INTEREST = "CREATE_CV_INTEREST"
export const CREATE_CV_LANGUAGE_LOADING = "CREATE_CV_LANGUAGE_LOADING"
export const CREATE_CV_LANGUAGE = "CREATE_CV_LANGUAGE"
export const CREATE_CV_RESUME_LOADING = "CREATE_CV_RESUME_LOADING"
export const CREATE_CV_RESUME = "CREATE_CV_RESUME"
export const CREATE_CV_SKILL_LOADING = "CREATE_CV_SKILL_LOADING"
export const CREATE_CV_SKILL = "CREATE_CV_SKILL"
export const CREATE_CV_CAREER_LOADING = "CREATE_CV_CAREER_LOADING"
export const CREATE_CV_CAREER = "CREATE_CV_CAREER"
export const CREATE_CV_COURSE_LOADING = "CREATE_CV_COURSE_LOADING"
export const CREATE_CV_COURSE = "CREATE_CV_COURSE"


//BOOKMARK: ========
export const ALL_BOOKMARK_LOADING = "ALL_BOOKMARK_LOADING"
export const ALL_BOOKMARKS = "ALL_BOOKMARK";
export const BOOKMARK_JOB_LOADING = "BOOKMARK_JOB_LOADING"
export const BOOKMARK_JOB = "BOOKMARK_JOB";


//OFFERS: ============
export const SENT_OFFERS_LOADING = "SENT_OFFERS_LOADING"
export const SENT_OFFERS = "SENT_OFFERS";
export const SENT_OFFERS_BY_JOB_LOADING = "SENT_OFFERS_BY_JOB_LOADING"
export const SENT_OFFERS_BY_JOB = "SENT_OFFERS_BY_JOB"
export const OFFERS_LOADING = " OFFERS_LOADING"
export const OFFERS = "OFFERS"
